apiVersion: 1
groups:
    - orgId: 1
      name: MertCPU
      folder: highcpu
      interval: 1m
      rules:
        - uid: desdp3uf0lpfkc
          title: highcpu
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)\r\n"
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          keepFiringFor: 1m
          annotations:
            summary: HighCPU
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
        - uid: fesdq2c6ffocgf
          title: highcpu
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                editorMode: code
                expr: "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)\r\n"
                instant: true
                interval: ""
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: 928f3e50-8078-4bfd-befb-6c554c5e03bb
          panelId: 1
          noDataState: NoData
          execErrState: Error
          for: 1m
          keepFiringFor: 1m
          annotations:
            __dashboardUid__: 928f3e50-8078-4bfd-befb-6c554c5e03bb
            __panelId__: "1"
            summary: highCPU
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
        - uid: desdqrglpf474c
          title: highCPU
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                editorMode: code
                expr: "rate(node_cpu_seconds_total{mode=\"user\"}[1m])\r\n"
                instant: true
                interval: ""
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: 928f3e50-8078-4bfd-befb-6c554c5e03bb
          panelId: 1
          noDataState: NoData
          execErrState: Error
          for: 1m
          keepFiringFor: 1m
          annotations:
            __dashboardUid__: 928f3e50-8078-4bfd-befb-6c554c5e03bb
            __panelId__: "1"
            summary: highCPU
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
