global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] #burada prometheus kendi kendine veri toplayacak yani self-monitoring

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] #localhost demiyoruz çünkü container içindeki diğer servise eriim sağlayacağız